Repository woowa-techcamp-2021/deal-2, pull requests merged in 2021-07, with the labels that each got.

#89 설정 : eslint, prettier, express 설정 완료
  app/.eslintrc.js
  app/.prettierrc
  app/app.js
  app/bin/www
  app/package-lock.json
  app/package.json
  app/public/index.html
  app/public/stylesheets/style.css
  app/routes/index.js
  app/routes/users.js
Labels: settings

#90 chore : www 문법 수정
  app/bin/www
Labels: hotfix

#100 fix : css-modules 설정
  client/package-lock.json
  client/package.json
  client/src/views/components/FAB/FAB.js
  client/src/views/components/categoryListItem/categoryListItem.css
  client/src/views/components/categoryListItem/categoryListItem.js
  client/src/views/components/icon/icon.js
  client/src/views/components/mainHeader/mainHeader.js
  client/src/views/pages/main/main.js
  client/src/views/styles/pages/common.css
  client/webpack.config.js
Labels: bug

#102 슬라이딩 애니메이션 구현
  client/src/index.html
  client/src/root.js
  client/src/services/replaceBothSideNodes.js
  client/src/services/slideAnimation.js
  client/src/views/pages/category.js
  client/src/views/pages/category/category.js
  client/src/views/pages/category/index.js
  client/src/views/pages/main/main.js
  client/src/views/styles/pages/common.css
Labels: front

#103 추가 : 이미지 박스 컴포넌트 구현
  client/src/views/components/categoryListItem/categoryListItem.css
  client/src/views/components/categoryListItem/categoryListItem.js
  client/src/views/components/imgBox/imgBox.css
  client/src/views/components/imgBox/imgBox.js
  client/src/views/components/imgBox/index.js
Labels: component, front

#104 추가 : 버튼 컴포넌트 구현
  client/src/images/add-green.svg
  client/src/images/close-green.svg
  client/src/views/components/FAB/index.js
  client/src/views/components/button/FAB.css
  client/src/views/components/button/FAB.js
  client/src/views/components/button/category.css
  client/src/views/components/button/category.js
  client/src/views/components/button/index.js
  client/src/views/components/button/large.css
  client/src/views/components/button/large.js
  client/src/views/components/button/location.css
  client/src/views/components/button/location.js
  client/src/views/components/button/medium.css
  client/src/views/components/button/medium.js
  client/src/views/components/button/status.css
  client/src/views/components/button/status.js
  client/src/views/components/button/tap.css
  client/src/views/components/button/tap.js
  client/src/views/components/categoryListItem/categoryListItem.js
  client/src/views/pages/main/main.js
Labels: component, front

#105 추가 : 카테고리 아이템 white, off-white, invisible 하나로 묶어서 컴포넌트화
  client/src/views/components/menuHeader/index.js
  client/src/views/components/menuHeader/menuHeader.css
  client/src/views/components/menuHeader/menuHeader.js
  client/src/views/pages/category/category.js
Labels: front

#106 추가 : 드롭다운
  client/src/views/components/modal/dropdown.css
  client/src/views/components/modal/dropdown.js
  client/src/views/components/modal/dropdownElement.css
  client/src/views/components/modal/dropdownElement.js
  client/src/views/components/modal/index.js
Labels: component, front

#107 추가 : 카테고리 페이지 구현 및 카테고리 리스트 아이템 컴포넌트 구현
  client/src/views/components/categoryListItem/categoryListItem.css
  client/src/views/components/categoryListItem/categoryListItem.js
  client/src/views/components/productListItem/index.js
  client/src/views/components/productListItem/productListItem.css
  client/src/views/components/productListItem/productListItem.js
  client/src/views/pages/category/category.css
  client/src/views/pages/category/category.js
  client/src/views/pages/main/main.js
Labels: front

#109 hotfix : css 모듈화 빼기
  client/src/views/components/button/FAB.js
  client/src/views/components/button/category.js
  client/src/views/components/button/large.js
  client/src/views/components/button/location.js
  client/src/views/components/button/medium.js
  client/src/views/components/button/status.js
  client/src/views/components/button/tap.js
  client/src/views/components/categoryListItem/categoryListItem.css
  client/src/views/components/categoryListItem/categoryListItem.js
  client/src/views/components/icon/icon.js
  client/src/views/components/imgBox/imgBox.css
  client/src/views/components/imgBox/imgBox.js
  client/src/views/components/mainHeader/mainHeader.css
  client/src/views/components/mainHeader/mainHeader.js
  client/src/views/components/menuHeader/menuHeader.css
  client/src/views/components/menuHeader/menuHeader.js
  client/src/views/components/modal/dropdown.js
  client/src/views/components/modal/dropdownElement.js
  client/src/views/components/productListItem/productListItem.css
  client/src/views/components/productListItem/productListItem.js
  client/src/views/pages/category/category.js
  client/src/views/pages/main/main.css
  client/src/views/pages/main/main.js
  client/src/views/styles/pages/common.css
  client/webpack.config.js
Labels: hotfix

#110 추가 : imgNav, imgNavigation 컴포넌트 추가
  client/src/services/changeActiveImgNav.js
  client/src/views/components/imgNav/imgNav.css
  client/src/views/components/imgNav/imgNav.js
  client/src/views/components/imgNav/index.js
  client/src/views/components/imgNavigation/imgNavigation.css
  client/src/views/components/imgNavigation/imgNavigation.js
  client/src/views/components/imgNavigation/index.js
  client/src/views/pages/category/category.js
Labels: component, front

#111 추가 : chatBubble 컴포넌트
  client/src/views/components/chatBubble/chatBubble.css
  client/src/views/components/chatBubble/chatBubble.js
  client/src/views/components/chatBubble/index.js
Labels: component, front

#112 추가 : chat-badge 컴포넌트
  client/src/views/components/chatBadge/chatBadge.css
  client/src/views/components/chatBadge/chatBadge.js
  client/src/views/components/chatBadge/index.js
Labels: component, front

#116 리펙토링 : after_render -> afterRender
  client/src/views/components/chatBadge/chatBadge.js
  client/src/views/components/imgNav/imgNav.js
  client/src/views/components/imgNavigation/imgNavigation.js
Labels: hotfix

#113 추가 : TabBar 컴포넌트 추가, tab 컴포넌트 리펙토링
  client/src/services/changeActiveComponent.js
  client/src/services/changeActiveImgNav.js
  client/src/views/components/button/index.js
  client/src/views/components/button/tab.css
  client/src/views/components/button/tab.js
  client/src/views/components/button/tap.css
  client/src/views/components/button/tap.js
  client/src/views/components/imgNav/imgNav.css
  client/src/views/components/imgNav/imgNav.js
  client/src/views/components/imgNavigation/imgNavigation.js
  client/src/views/components/tabBar/index.js
  client/src/views/components/tabBar/tabBar.css
  client/src/views/components/tabBar/tabBar.js
Labels: component, front

#117 추가 : chatListItem 컴포넌트 추가 및 관련 컴포넌트 스타일 수정
  client/src/views/components/chatBadge/chatBadge.css
  client/src/views/components/chatBadge/chatBadge.js
  client/src/views/components/chatListItem/chatListItem.css
  client/src/views/components/chatListItem/chatListItem.js
  client/src/views/components/chatListItem/index.js
  client/src/views/components/menuHeader/menuHeader.css
Labels: component, front

#118 추가 : infoProduct 컴포넌트
  client/src/views/components/button/status.css
  client/src/views/components/imgBox/imgBox.css
  client/src/views/components/infoProduct/index.js
  client/src/views/components/infoProduct/infoProduct.css
  client/src/views/components/infoProduct/infoProduct.js
Labels: component, front

#114 추가 : alert 모달
  client/src/views/components/modal/alert.css
  client/src/views/components/modal/alert.js
  client/src/views/components/modal/index.js
Labels: component, front

#120 추가 : chatbar 컴포넌트
  client/src/images/send-green.svg
  client/src/images/send.svg
  client/src/services/changeSendIcon.js
  client/src/views/components/chatBar/chatBar.css
  client/src/views/components/chatBar/chatBar.js
  client/src/views/components/chatBar/index.js
  client/src/views/components/textInput/index.js
  client/src/views/components/textInput/large.css
  client/src/views/components/textInput/large.js
  client/src/views/components/textInput/medium.css
  client/src/views/components/textInput/medium.js
Labels: component, front

#123 리펙토링 : 겹치는 컴포넌트의 통합
  client/src/views/components/button/button.css
  client/src/views/components/button/button.js
  client/src/views/components/button/index.js
  client/src/views/components/button/large.css
  client/src/views/components/button/medium.css
  client/src/views/components/button/medium.js
  client/src/views/components/chatBar/chatBar.js
  client/src/views/components/textInput/index.js
  client/src/views/components/textInput/large.css
  client/src/views/components/textInput/large.js
  client/src/views/components/textInput/medium.js
  client/src/views/components/textInput/textInput.css
  client/src/views/components/textInput/textInput.js
Labels: refactor

#122 메뉴 페이지 구현 완료 : 탭 이용해서 슬라이딩 애니메이션 추가
  client/src/root.js
  client/src/services/getNodeIndex.js
  client/src/services/menuSlideAnimation.js
  client/src/services/toggleDisableChildrenButton.js
  client/src/views/components/button/tab.css
  client/src/views/components/mainHeader/mainHeader.js
  client/src/views/components/menuTab/chatList/chatList.js
  client/src/views/components/menuTab/chatList/index.js
  client/src/views/components/menuTab/likeList/index.js
  client/src/views/components/menuTab/likeList/likeList.js
  client/src/views/components/menuTab/sellList/index.js
  client/src/views/components/menuTab/sellList/sellList.js
  client/src/views/components/tabBar/tabBar.js
  client/src/views/pages/menu/index.js
  client/src/views/pages/menu/menu.css
  client/src/views/pages/menu/menu.js
Labels: front

#124 추가 : imgButton
  client/src/images/close.svg
  client/src/images/image.svg
  client/src/views/components/imgButton/add/addImgButton.css
  client/src/views/components/imgButton/add/addImgButton.js
  client/src/views/components/imgButton/add/index.js
  client/src/views/components/imgButton/delete/deleteImgButton.css
  client/src/views/components/imgButton/delete/deleteImgButton.js
  client/src/views/components/imgButton/delete/index.js
Labels: component, front

#125 추가 : 글쓰기 페이지 레이아웃 및 locationBar
  client/src/images/map-pin-black.svg
  client/src/root.js
  client/src/services/fitScroll.js
  client/src/views/components/button/category.css
  client/src/views/components/locationBar/index.js
  client/src/views/components/locationBar/locationBar.css
  client/src/views/components/locationBar/locationBar.js
  client/src/views/pages/main/main.js
  client/src/views/pages/write/index.js
  client/src/views/pages/write/write.css
  client/src/views/pages/write/write.js
Labels: component, front

#127 추가 : productBar 컴포넌트
  client/src/views/components/productBar/index.js
  client/src/views/components/productBar/productBar.css
  client/src/views/components/productBar/productBar.js
Labels: component, front

#128 추가 : infoSaler 컴포넌트
  client/src/views/components/infoSaler/index.js
  client/src/views/components/infoSaler/infoSaler.css
  client/src/views/components/infoSaler/infoSaler.js
Labels: component, front

#129 추가 : inputPopup 컴포넌트
  client/src/services/changeConfirmButton.js
  client/src/views/components/modal/index.js
  client/src/views/components/modal/inputPopup.css
  client/src/views/components/modal/inputPopup.js
Labels: component, front

#132 추가 : chatListPage 페이지 구현
  client/src/root.js
  client/src/views/pages/chatList/chatListPage.css
  client/src/views/pages/chatList/chatListPage.js
  client/src/views/pages/chatList/index.js
Labels: front

#134 변경 : 슬라이딩 애니메이션의 변경
  client/src/root.js
  client/src/views/pages/category/category.css
  client/src/views/pages/menu/menu.css
Labels: front

#131 추가 : 사진 추가 삭제 기능, 스크롤 기능 구현, 카테고리 토글 기능 구현
  client/src/services/handleImgFiles.js
  client/src/services/horizontalScroll.js
  client/src/services/toggleCategory.js
  client/src/views/components/button/category.css
  client/src/views/components/imgButton/add/addImgButton.css
  client/src/views/components/imgButton/add/addImgButton.js
  client/src/views/components/imgButton/delete/deleteImgButton.js
  client/src/views/pages/write/write.css
  client/src/views/pages/write/write.js
Labels: front

#135 추가 : 채팅 상세페이지
  client/src/images/log-out.svg
  client/src/root.js
  client/src/views/pages/chatDetail/chatDetail.css
  client/src/views/pages/chatDetail/chatDetail.js
  client/src/views/pages/chatDetail/index.js
Labels: front

#137 추가 : 글쓰기 페이지 필수 항목 체크
  client/src/images/check-mint.svg
  client/src/images/check.svg
  client/src/services/essentialInfoCheck.js
  client/src/views/pages/write/write.css
  client/src/views/pages/write/write.js
Labels: front

#138 Feature/23
  client/src/services/checkSignup.js
  client/src/views/components/button/button.js
  client/src/views/components/textInput/textInput.js
  client/src/views/pages/signup/signup.js
Labels: front

#141 추가 : 내 동네 모달
  client/src/services/changeDropdownDisplay.js
  client/src/views/components/mainHeader/mainHeader.css
  client/src/views/components/mainHeader/mainHeader.js
  client/src/views/components/modal/dropdown.css
  client/src/views/components/modal/dropdown.js
  client/src/views/components/modal/dropdownElement.css
  client/src/views/pages/main/main.js
Labels: front

#139 추가 : 제품 상세 페이지
  client/src/images/chevron-left-white.svg
  client/src/images/more-vertical-white.svg
  client/src/root.js
  client/src/views/components/imgBox/imgBox.css
  client/src/views/components/menuHeader/menuHeader.css
  client/src/views/pages/productDetail/index.js
  client/src/views/pages/productDetail/productDetail.css
  client/src/views/pages/productDetail/productDetail.js
Labels: front

#146 추가 : 백엔드 회원가입 처리
  client/src/services/checkSignup.js
  client/src/views/pages/signup/signup.js
  server/controller/signup.js
  server/controllers/signup.js
  server/db/index.js
  server/middlewares/checkSignup.js
  server/routes/signup.js
Labels: back

#149 추가 : (프론트, 백) 로그인, 로그아웃 처리
  client/src/apis/index.js
  client/src/views/components/mainHeader/mainHeader.js
  client/src/views/pages/login/login.js
  client/src/views/pages/myinfo/myinfo.js
  client/src/views/pages/signup/signup.js
  server/app.js
  server/controllers/login.js
  server/controllers/signup.js
  server/package.json
  server/routes/login.js
Labels: back, front

#153 추가 : 회원가입, 로그인, 글쓰기 기능 구현
  client/src/apis/index.js
  client/src/services/essentialInfoCheck.js
  client/src/services/handleImgFiles.js
  client/src/views/components/imgButton/delete/deleteImgButton.css
  client/src/views/components/imgButton/delete/deleteImgButton.js
  client/src/views/components/locationBar/locationBar.js
  client/src/views/pages/signup/signup.js
  client/src/views/pages/write/write.css
  client/src/views/pages/write/write.js
  server/app.js
  server/controllers/product.js
  server/controllers/signup.js
  server/controllers/upload.js
  server/middlewares/awsUpload.js
  server/package-lock.json
  server/package.json
  server/routes/product.js
  server/routes/upload.js
Labels: back, front

#154 리펙토링 : for of 관련 eslint 규칙 off
  client/.eslintrc.js
  client/src/services/handleImgFiles.js
  client/src/views/components/imgNavigation/imgNavigation.js
  client/src/views/components/menuTab/chatList/chatList.js
  client/src/views/components/menuTab/likeList/likeList.js
  client/src/views/components/menuTab/sellList/sellList.js
  client/src/views/components/modal/dropdown.js
  client/src/views/components/tabBar/tabBar.js
  client/src/views/pages/category/category.js
  client/src/views/pages/write/write.js
  server/.eslintrc.js
  server/controllers/product.js
Labels: settings

#156 리펙토링 : 백엔드 구조 변경
  server/app.js
  server/controllers/login.js
  server/controllers/product.js
  server/controllers/signup.js
  server/controllers/upload.js
  server/db/index.js
  server/image/image.controller.js
  server/image/image.middleware.upload.js
  server/login/login.controller.js
  server/login/login.service.js
  server/middlewares/checkSignup.js
  server/product/product.controller.js
  server/product/product.service.js
  server/public/index.html
  server/public/stylesheets/style.css
  server/routes/index.js
  server/routes/login.js
  server/routes/product.js
  server/routes/signup.js
  server/routes/upload.js
  server/signup/signup.controller.js
  server/signup/signup.middleware.check.js
  server/signup/signup.service.js
Labels: settings

#158 리펙토링 : 서비스 폴더 구조 변경
  client/src/root.js
  client/src/services/chatDetail/changeSendIcon.js
  client/src/services/common/changeActiveComponent.js
  client/src/services/common/getNodeIndex.js
  client/src/services/common/slideAnimation.js
  client/src/services/common/utils.js
  client/src/services/main/changeDropdownDisplay.js
  client/src/services/menu/menuSlideAnimation.js
  client/src/services/menu/toggleDisableChildrenButton.js
  client/src/services/replaceBothSideNodes.js
  client/src/services/signup/checkSignup.js
  client/src/services/town/changeConfirmButton.js
  client/src/services/write/essentialInfoCheck.js
  client/src/services/write/fitScroll.js
  client/src/services/write/handleImgFiles.js
  client/src/services/write/horizontalScroll.js
  client/src/services/write/toggleCategory.js
  client/src/views/components/chatBar/chatBar.js
  client/src/views/pages/main/main.js
  client/src/views/pages/menu/menu.js
  client/src/views/pages/signup/signup.js
  client/src/views/pages/write/write.js
Labels: front, settings

#159 추가 : 메인페이지 관련 동작들 ( 품목 받아오기, 품목 렌더링 관련 함수들(하트변경,시간변경), 품목 받아오는 api 추가)
  client/src/apis/index.js
  client/src/services/common/toggleHeartIcon.js
  client/src/services/common/utils.js
  client/src/services/main/getProduct.js
  client/src/views/components/icon/icon.css
  client/src/views/components/imgBox/imgBox.js
  client/src/views/components/mainHeader/mainHeader.js
  client/src/views/components/productListItem/productListItem.js
  client/src/views/pages/main/main.js
  server/product/product.controller.js
  server/product/product.service.js
Labels: back, front

#167 추가 : clean-webpack-plugin
  client/package-lock.json
  client/package.json
  client/webpack.config.js
Labels: settings

#168 추가 : 카테고리 페이지에서 카테고리 클릭시 메인 페이지에 관련 상품 렌더링
  client/src/root.js
  client/src/services/common/utils.js
  client/src/services/main/getProduct.js
  client/src/views/components/categoryListItem/categoryListItem.css
  client/src/views/pages/category/category.js
  server/product/product.controller.js
  server/product/product.service.js
Labels: back, front

#169 추가 : 동네 정보 가져오기, 동네 설정 페이지
  client/src/root.js
  client/src/services/main/getTown.js
  client/src/services/town/getTowns.js
  client/src/views/components/mainHeader/mainHeader.js
  client/src/views/components/modal/dropdown.js
  client/src/views/pages/productDetail/index.js
  client/src/views/pages/town/index.js
  client/src/views/pages/town/town.css
  client/src/views/pages/town/town.js
  server/app.js
  server/signup/signup.controller.js
  server/signup/signup.middleware.check.js
  server/signup/signup.service.js
  server/town/town.controller.js
  server/town/town.service.js
Labels: back, front

#170 추가 : 상품 상세 페이지 기본 기능
  client/src/services/common/imageSlider.js
  client/src/services/common/productOnClick.js
  client/src/services/common/toggleHeartIcon.js
  client/src/services/common/utils.js
  client/src/services/main/getProduct.js
  client/src/views/components/imgBox/imgBox.css
  client/src/views/components/imgBox/imgBox.js
  client/src/views/components/imgNav/imgNav.css
  client/src/views/components/imgNavigation/imgNavigation.js
  client/src/views/components/productBar/productBar.js
  client/src/views/components/productListItem/productListItem.js
  client/src/views/pages/productDetail/productDetail.css
  client/src/views/pages/productDetail/productDetail.js
  server/product/product.controller.js
  server/product/product.service.js
Labels: front

#175 추가 : 모달에 있는 동네 클릭 시 해당 동네 물건 받아오기
  client/src/services/main/changeDropdownDisplay.js
  client/src/views/components/modal/dropdown.js
  server/product/product.service.js
Labels: back, front

#176 세팅 : pm2 환경설정 및 express-session cookie-session으로 교체
  server/app.js
  server/ecosystem.config.js
  server/package-lock.json
  server/package.json
Labels: deploy

#177 추가 : 판매 목록 api 및 버그 수정, 카테고리+동네로 물품 가져오기
  client/src/root.js
  client/src/services/menu/menuSlideAnimation.js
  client/src/views/components/mainHeader/mainHeader.js
  client/src/views/components/menuTab/sellList/sellList.js
  client/src/views/pages/main/main.js
  client/src/views/pages/menu/menu.css
  client/src/views/pages/menu/menu.js
  client/src/views/pages/myinfo/myinfo.js
  client/src/views/pages/productDetail/productDetail.js
  server/app.js
  server/sellList/sellList.controller.js
  server/sellList/sellList.service.js
Labels: back, bug, front

#178 chore : dotenv 와 defineplugin이용 배포와 dev api url 구분
  client/package-lock.json
  client/package.json
  client/src/apis/index.js
  client/src/views/pages/signup/signup.js
  client/webpack.config.js
Labels: deploy

#180 fix : 최초 로그인 시 '전체'가 출력되도록 변경
  client/src/views/components/mainHeader/mainHeader.js
Labels: bug

#182 추가 : 데브 api url 변경 및 comming soon modal 추가
  client/src/views/components/commingSoonModal/commingSoonModal.css
  client/src/views/components/commingSoonModal/commingSoonModal.js
  client/src/views/components/commingSoonModal/index.js
  client/src/views/components/menuTab/chatList/chatList.js
  client/src/views/components/productBar/productBar.js
  client/src/views/pages/chatDetail/chatDetail.js
  client/src/views/pages/chatList/chatListPage.js
  client/src/views/pages/productDetail/productDetail.js
  client/webpack.config.js
Labels: front

#184 추가 : 글쓰기 페이지에서 동네 정보 선택
  client/src/index.html
  client/src/services/write/essentialInfoCheck.js
  client/src/services/write/getTown.js
  client/src/views/components/locationBar/locationBar.css
  client/src/views/components/locationBar/locationBar.js
  client/src/views/pages/write/write.js
Labels: front

#185 fix : 새로고침 시 메인 화면으로 가게 변경
  client/src/views/components/menuHeader/menuHeader.js
  client/src/views/pages/productDetail/productDetail.js
Labels: bug, hotfix

#186 추가 : 상품 상세페이지, 판매목록 케밥 버튼 클릭시 모달 추가
  client/src/views/components/menuTab/sellList/sellList.js
  client/src/views/components/modal/productDropdown.css
  client/src/views/components/modal/productDropdown.js
  client/src/views/pages/menu/menu.css
  client/src/views/pages/productDetail/productDetail.js
Labels: front

#187 추가 : 백엔드 서버 시작 시 테이블 생성
  server/db/index.js
Labels: back, settings

#188 hotfix : 가격 쉼표와 원 표시
  client/src/views/components/productBar/productBar.js
  client/src/views/components/productListItem/productListItem.js
Labels: hotfix

#189 hotfix : 전체 동네 추가, 미구현 기능에 커밍순 모달 추가
  client/src/views/components/menuTab/likeList/likeList.js
  client/src/views/components/modal/dropdown.js
  client/src/views/pages/signup/signup.js
Labels: hotfix

#191 추가 : 프로덕트 삭제 기능
  client/src/apis/index.js
  client/src/views/components/menuTab/sellList/sellList.js
  client/src/views/components/modal/alert.js
  client/src/views/components/modal/productDropdown.js
  client/src/views/pages/productDetail/productDetail.js
  server/product/product.controller.js
  server/product/product.service.js
Labels: back, front

#193 추가 : 이미지 압축
  client/src/services/write/compressImage.js
  client/src/services/write/handleImgFiles.js
  client/src/views/components/imgButton/add/addImgButton.js
  server/db/index.js
Labels: front

#195 문서 : Readme 업데이트
  README.md
Labels: docs
